import type { Metadata } from 'next';
import Link from 'next/link';
import { Scale } from 'lucide-react';

export const metadata: Metadata = {
    title: 'Terms of Service | LegaldocsGPT',
    description: 'Read the LegaldocsGPT Terms of Service before using the platform.',
};

const LAST_UPDATED = 'April 9, 2026';

function Section({ title, children }: { title: string; children: React.ReactNode }) {
    return (
        <section className="space-y-3">
            <h2 className="text-xl font-semibold text-slate-900">{title}</h2>
            <div className="text-slate-600 leading-relaxed space-y-2">{children}</div>
        </section>
    );
}

export default function TermsPage() {
    return (
        <div className="min-h-screen bg-white">
            {/* Header */}
            <div className="bg-slate-50 border-b border-slate-200">
                <div className="mx-auto max-w-3xl px-6 py-12">
                    <Link href="/" className="inline-flex items-center gap-2 text-indigo-600 hover:text-indigo-700 text-sm font-medium mb-6">
                        <Scale size={16} />
                        LegaldocsGPT
                    </Link>
                    <h1 className="text-4xl font-bold text-slate-900">Terms of Service</h1>
                    <p className="mt-2 text-slate-500 text-sm">Last updated: {LAST_UPDATED}</p>
                </div>
            </div>

            {/* Content */}
            <div className="mx-auto max-w-3xl px-6 py-12 space-y-10">

                <p className="text-slate-600 leading-relaxed">
                    By accessing or using LegaldocsGPT (&ldquo;the Service&rdquo;), you agree to be bound by
                    these Terms of Service. If you do not agree, do not use the Service.
                </p>

                <Section title="1. Description of Service">
                    <p>
                        LegaldocsGPT is an AI-assisted document generation platform that produces draft legal
                        documents based on professional templates and user-provided information. The Service is
                        designed to assist with document drafting and is not a substitute for legal advice.
                    </p>
                </Section>

                <Section title="2. Not Legal Advice">
                    <p>
                        <strong>LegaldocsGPT is not a law firm and does not provide legal advice.</strong> The
                        documents generated by the Service are starting points for drafting purposes only. You
                        should consult a qualified attorney before relying on any document generated by the
                        Service for legal, business, or personal purposes.
                    </p>
                </Section>

                <Section title="3. Eligibility">
                    <p>
                        You must be at least 18 years old and have the legal capacity to enter into binding
                        agreements to use the Service. By using the Service, you represent that you meet these
                        requirements.
                    </p>
                </Section>

                <Section title="4. User Accounts">
                    <p>
                        You are responsible for maintaining the confidentiality of your account credentials and
                        for all activity that occurs under your account. Notify us immediately at
                        support@legaldocsgpt.com if you suspect unauthorized use of your account.
                    </p>
                </Section>

                <Section title="5. Intellectual Property">
                    <p>
                        Documents you generate using the Service are yours. You retain ownership of any content
                        you provide as input. LegaldocsGPT retains ownership of the platform, templates, and
                        underlying technology. You may not copy, sell, or redistribute the Service&apos;s
                        templates or source code.
                    </p>
                </Section>

                <Section title="6. Prohibited Uses">
                    <p>You agree not to use the Service to:</p>
                    <ul className="list-disc pl-5 space-y-1">
                        <li>Generate fraudulent, deceptive, or illegal documents</li>
                        <li>Violate any applicable law or third-party rights</li>
                        <li>Attempt to reverse engineer, scrape, or overload the Service</li>
                        <li>Use the Service on behalf of others without their authorization</li>
                    </ul>
                </Section>

                <Section title="7. Limitation of Liability">
                    <p>
                        To the fullest extent permitted by law, LegaldocsGPT shall not be liable for any
                        indirect, incidental, special, or consequential damages arising from your use of, or
                        inability to use, the Service - including damages resulting from reliance on any
                        AI-generated document without independent legal review.
                    </p>
                </Section>

                <Section title="8. Termination">
                    <p>
                        We reserve the right to suspend or terminate your account for violation of these Terms
                        or for any other reason at our discretion, with or without notice.
                    </p>
                </Section>

                <Section title="9. Changes to Terms">
                    <p>
                        We may update these Terms from time to time. We will notify you of material changes by
                        posting the new Terms on this page and updating the &ldquo;Last updated&rdquo; date.
                        Continued use of the Service after changes constitutes acceptance.
                    </p>
                </Section>

                <Section title="10. Contact">
                    <p>
                        Questions about these Terms? Contact us at{' '}
                        <a href="mailto:support@legaldocsgpt.com" className="text-indigo-600 hover:underline">
                            support@legaldocsgpt.com
                        </a>
                        .
                    </p>
                </Section>

                <div className="border-t border-slate-200 pt-8 text-sm text-slate-400 flex gap-6">
                    <Link href="/privacy" className="hover:text-slate-600">Privacy Policy</Link>
                    <Link href="/" className="hover:text-slate-600">Home</Link>
                </div>
            </div>
        </div>
    );
}
